Fix --format

diff --git a/vzvol b/vzvol
--- a/vzvol
+++ b/vzvol
@@ -252,8 +252,9 @@ getargz() {
 				exit
 			;;
 			--format)
-				if [ $( zfs list -t volume | awk '{print $1}' | grep -v "NAME" | grep -q "${3}" ) = 1 ]; then
-					echo "Error, zvol ${2} does not exist."
+				( zfs list -t volume | awk '{print $1}' | grep -v "NAME" | grep -q "${3}" )
+				if [ $? = 1 ]; then
+					echo "Error, zvol ${3} does not exist."
 					echo "Try running vzvol --list or zfs list -t volume to see the available zvols on the system."
 					return 1
 				else
